In [2]:
#Step 1: Creating Vectors
import numpy as np

# Two tiny 3D vectors
a = np.array([2, 1, 3])
b = np.array([1, 3, 3])
print(a)
print(b)

[2 1 3]
[1 3 3]


In [3]:
#Step 2: Vector Operations (Addition and Subtraction)
add_ab = a + b
sub_ab = a - b
print(add_ab)
print(sub_ab)

[3 4 6]
[ 1 -2  0]


In [4]:
#Step 3: Dot Product (Similarity of Direction)
# Manual dot product: sum of pairwise products
dot = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]

dot_np = a@b # np.dot(a,b)
print(dot)
print(dot_np)

14
14


In [5]:
#Step 4: Norms (Length or Magnitude of a Vector)
# L2 norm, the usual length
l2_a = np.linalg.norm(a)
print(l2_a)
l1_a = np.linalg.norm(a, ord = 1)
print(l1_a)

3.7416573867739413
6.0


In [6]:
#Step 5: Normalizing a Vector (Unit Vector)
unit_a = a/np.linalg.norm(a)
len_unit_a = np.linalg.norm(unit_a)
print(unit_a)
print(len_unit_a)

[0.53452248 0.26726124 0.80178373]
1.0
