### Ndarray creation from Existing data

In [ ]:
#From list
import numpy as np
lst = [10,20,30,40,50.5]

arr = np.array(lst, dtype=np.int64)
print(arr) 
print(type(arr))
print(arr.dtype)

mixed_lst = [10,20.5,'30',40,'fifty']
#mixed_arr = np.array(mixed_lst)
#print(mixed_arr)
#print(type(mixed_arr))
#print(mixed_arr.dtype)


matrix = [[1,2,3], #Row 1
          [4,5,6]] #Row 2

mixed_arr = np.array(matrix)
print(mixed_arr)
print(type(mixed_arr))
print(mixed_arr.dtype)
print(mixed_arr.shape) #2 rows, 3 columns
print(mixed_arr.ndim)  #2 dimensions

[10 20 30 40 50]
<class 'numpy.ndarray'>
int64
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [4]:
#Tuple to array

tup = (100,200,300,400)

arr = np.array(tup,dtype=np.int32)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[100 200 300 400]
<class 'numpy.ndarray'>
int16
(4,)
1


In [5]:
#Set to array
st = {1,2,3}

#Tuple can't be converted to array directly, it needs to be converted to list first
arr = np.array(list(st))
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

int64
[1 2 3]
<class 'numpy.ndarray'>
int16
(3,)
1


In [6]:
#Dictionary to array
dct = {'a':1,'b':2,'c':3}

keys = dct.keys()
values = dct.values()
items = dct.items()

#Keys to array
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1


In [8]:
#Values to array
arr = np.array(list(values))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1
3


In [9]:
#Items to array
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['a' '1']
 ['b' '2']
 ['c' '3']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6
