#### Array creation with random values


In [ ]:
#np.random.rand(shape)
import numpy as np

arr  = np.random.rand(2,3)

print(arr)
print(type(arr))
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)

[[0.02188809 0.96348407 0.65247745]
 [0.4560645  0.95128449 0.12958712]]
<class 'numpy.ndarray'>
(2, 3)
float64
2
6


In [ ]:
#Integar Values
#np.random.randint(start , end , shape)

arr = np.random.randint(1,100,(3,))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[32 22 50]
<class 'numpy.ndarray'>
int32
(3,)
1
3


In [16]:
#Float Values
#np.random.randint(start , end , shape)

arr = np.random.uniform(50,100,(3,4))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[79.93639441 69.93083249 96.66382321 75.00596751]
 [54.885025   79.37506298 93.98231693 56.66667739]
 [81.07094452 72.45811524 64.2069153  86.16170146]]
<class 'numpy.ndarray'>
float64
(3, 4)
2
12
