#### Array creation with range function


In [ ]:
#np.arange(first,end,step) -> SImilar to range function
import numpy as np
arr = np.arange(1, 10, 1).reshape(3,3)


print(arr)
print(type(arr))
print(arr.shape) 
print(arr.dtype)
print(arr.ndim)
print(arr.size)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)
int64
2
9


In [ ]:
#np.linespace(start , end(included) , n )

arr = np.linspace(1, 10, 10)


print(arr)
print(type(arr))
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)

[ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]
<class 'numpy.ndarray'>
(9,)
float64
1
9


In [13]:
#np.loagspace(start , end(included) , n )
arr = np.logspace(0, 4, 6, base=2)

print(arr)

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]
