### Creating Matrix for linear Algebra

In [ ]:
import numpy as np

diagonal_matrix = np.diag([1,1,1,1,1])

print (diagonal_matrix)
print(diagonal_matrix.shape) 


[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
(5, 5)


##### Identity Matrix


In [ ]:
identity_mat = np.eye(3)
print(identity_mat)
print(identity_mat.shape)

#np.eye(row , column)

mat = np.eye(3,4)
print(mat)

mat = np.eye(3,4,-1)
print(mat)

mat = np.eye(3,4,2)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
