In [15]:
import numpy as np

x = np.array([10, 25, 30, 49, 50])
y = np.array([1, 2, 3, 4, 5])

add = x + y
sub = x - y
mul = x * y
div = x / y
rem = x % y

print(add)  # Output: [10, 20, 30, 40, 50, 1, 2, 3, 4, 5]
print(sub)  # Output: [9, 18, 27, 36, 45]
print(mul)  # Output: [10, 40, 90, 160
print(div)  # Output: [10. 10. 10. 10. 10.]
print(rem)  # Output: [0, 0, 0, 0, 0]

[11 27 33 53 55]
[ 9 23 27 45 45]
[ 10  50  90 196 250]
[10.   12.5  10.   12.25 10.  ]
[0 1 0 1 0]


# Mathematical Function


In [16]:
# Trigonometrical functions

# sin cos tan takes values in radians

sin_val = np.sin(x)
print(sin_val)  

cos_val = np.cos(x)
print(cos_val)

deg_con = np.rad2deg(x)
print(deg_con)

rad_con = np.deg2rad(deg_con)
print(rad_con)

[-0.54402111 -0.13235175 -0.98803162 -0.95375265 -0.26237485]
[-0.83907153  0.99120281  0.15425145  0.30059254  0.96496603]
[ 572.95779513 1432.39448783 1718.87338539 2807.49319614 2864.78897565]
[10. 25. 30. 49. 50.]


In [17]:
# Log

base_10_log_val = np.log10(x)
print(base_10_log_val)

base_2_log_val = np.log2(x)
print(base_2_log_val)

sqrt_val = np.sqrt(x)
print(sqrt_val)

[1.         1.39794001 1.47712125 1.69019608 1.69897   ]
[3.32192809 4.64385619 4.9068906  5.61470984 5.64385619]
[3.16227766 5.         5.47722558 7.         7.07106781]


In [19]:
# Different

s = np.sum(x)
print(s)

cumul = np.cumulative_sum(x)
print(cumul)


164
[ 10  35  65 114 164]
