In [12]:
import numpy as np

arr = np.random.randint(1, 100, size=(10,5))  # Sample - 10 , features = 5
arr.shape

b = arr.reshape(5, 10)  # Reshaping to 5 , 10
b.shape
b.ndim
print(b)

flatten = b.flatten()  # Flattening the array
flatten.shape
flatten.ndim
print(flatten)

col_wise = np.ravel(b , order = 'F')  # Converting to 1D using ravel

col_wise = np.ravel(b , order = 'F')  # Converting to 1D using ravel
print(col_wise)

[[93 70 79 60 85 80 13 51 39 12]
 [98 46 95  9 13 66 35 79 86 40]
 [44 22 83 36 10  5 27 27 22 14]
 [39 36 46 69 13  9 67 49 95 92]
 [73 40 38 74 70  8 89 96  3 67]]
[93 70 79 60 85 80 13 51 39 12 98 46 95  9 13 66 35 79 86 40 44 22 83 36
 10  5 27 27 22 14 39 36 46 69 13  9 67 49 95 92 73 40 38 74 70  8 89 96
  3 67]
[93 98 44 39 73 70 46 22 36 40 79 95 83 46 38 60  9 36 69 74 85 13 10 13
 70 80 66  5  9  8 13 35 27 67 89 51 79 27 49 96 39 86 22 95  3 12 40 14
 92 67]


In [13]:
a = np.random.randint(1, 10, size=(2,3)) 
b = np.random.randint(20, 30, size=(2,3)) 

print(a)
print(b)

[[8 1 2]
 [1 3 5]]
[[21 22 26]
 [27 21 29]]


### Concatenate

In [16]:
con_row = np.concatenate((a,b), axis=0)  # Concatenating along rows
print(con_row)

con_col = np.concatenate((a,b), axis=1)  # Concatenating along rows
print(con_col)

[[ 8  1  2]
 [ 1  3  5]
 [21 22 26]
 [27 21 29]]
[[ 8  1  2 21 22 26]
 [ 1  3  5 27 21 29]]


In [20]:
x = np.random.randint(1, 10, size=(2,3)) 
y = np.random.randint(20, 30, size=(1,3)) 

r = np.concatenate((x,y), axis=0)  # Row wise concatenation
print(r)
c = np.concatenate((x,y), axis=1)  # Column wise concatenation
print(c)

[[ 2  2  6]
 [ 1  6  1]
 [25 25 29]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1