In [ ]:
import numpy as np

x = np.array([10, 25, 30, 49, 50])
z = x.copy()

z.sort()
print(z)

[10 10 25 49 50]


In [8]:
print(x)

sort_arr = np.sort(x)
print(sort_arr)

print(x)

[10 25 10 49 50]
[10 10 25 49 50]
[10 25 10 49 50]


#### 2d Array Sorting

In [10]:
mat = np.array([[10,3,5] , [8,4,9]])

# horizon axis = 1
hor_sort = np.sort(mat, axis=1)
print(hor_sort)
ver_sort = np.sort(mat, axis=0)
print(ver_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]
