In [3]:
import numpy as np

x = np.array([10, 25, 10, 19, 100])
print(x)

ind = np.where(x > 20 , x , 0)
print(ind)

ind = np.where(x == 19)
print(ind)

[ 10  25  10  19 100]
[  0  25   0   0 100]
(array([3]),)


In [4]:
mat = np.array([[10,3,5] , [8,4,9]])
print(mat)

ind = np.where(mat > 5)
print(ind)

arr = np.where(mat>8,mat,0)
print(arr)

[[10  3  5]
 [ 8  4  9]]
(array([0, 1, 1]), array([0, 0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [7]:
maxi_value_ind = np.argmax(x)
print(maxi_value_ind)

y = np.array([10, 100, 10, 19, 100])

mini_value_ind = np.argmin(y)
print(mini_value_ind)

4
0
