In [4]:
import numpy as np

#1d array
arr1 = np.array([1,2,3,4,5])

arr1_mod = arr1[1:4].copy()
arr1[1] = 2 

arr1_mod[2] = 200

print(arr1_mod)
print(arr1)

arr1_mod[0] = 100
print(arr1_mod)

[  2   3 200]
[1 2 3 4 5]
[100   3 200]


##### Advanced Indexing

In [14]:
lst = np.array([10,20,30,40,50])

values = lst[[0,4]]

#print(values)

arr2 = np.array([ [1,2,3],
                 [4,5,6]])

print(arr2)
print(arr2[[0,1] , [1,2]])
print(arr2[arr2 > 2])
print(arr2[arr2 < 2])

arr2 [arr2>2] = 0
print(arr2)

[[1 2 3]
 [4 5 6]]
[2 6]
[3 4 5 6]
[1]
[[1 2 0]
 [0 0 0]]


In [18]:
arr = np.array([[10,20,30] , [100,200,300]] )

print(arr)

# for i in arr:
#     for j in i:
#         print(j)

for i in np.nditer(arr):
    print(i)

[[ 10  20  30]
 [100 200 300]]
10
20
30
100
200
300
