### ndarray from scratch


In [14]:
import numpy as np

# 3d Array
arr3 = np.array([
    #1st floor
    [ [1,2,3], # 1st row
    [4,5,6] ], # 2nd row
    
    #2nd floor
    [ [7,8,9], # 1st row
    [10,11,12]], # 2nd row
    
    #3rd floor
     [[7,8,9], # 1st row
    [10,11,12]] # 2nd row
    
     ])


#np.zeros

arr = np.zeros((2,3),dtype=np.int8)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.zeros_like(arr3)
print(arr)
print(arr.shape)

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
int8
(2, 3)
2
6
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(3, 2, 3)


In [15]:
#np.ones

# 3d Array
arr3 = np.array([
    #1st floor
    [ [1,2,3], # 1st row
    [4,5,6] ], # 2nd row
    
    #2nd floor
    [ [7,8,9], # 1st row
    [10,11,12]], # 2nd row
    
    #3rd floor
     [[7,8,9], # 1st row
    [10,11,12]] # 2nd row
    
     ])


#np.zeros

arr = np.ones((2,3),dtype=np.int8)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.ones_like(arr3)
print(arr)
print(arr.shape)

[[1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
int8
(2, 3)
2
6
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [19]:
#np.empty

arr = np.empty((4,3),dtype=np.int8)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.empty_like(arr3)
print(arr)
print(arr.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
int8
(4, 3)
2
12
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [23]:
#np.full

arr = np.full((4,3),np.inf)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.full_like(arr3,np.inf,dtype=np.float64)
print(arr)
print(arr.shape)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]
<class 'numpy.ndarray'>
float64
(4, 3)
2
12
[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
(3, 2, 3)
