### Indexing and Slicing

In [4]:
import numpy as np

#1d array
arr1 = np.array([1,2,3,4,5])


# arr1[2] = 100 
# print(arr1)

# print(arr1[2])

#2d Array
# arr2 = np.array([ [1,2,3],
#                   [4,5,6]])
# print(arr2)
# print(arr2[0][2])  # Accessing element at 2nd row, 3rd column

In [18]:
#1dSlicing

arr1_mod = arr1[1:4]
#print(arr1_mod)

#2d Slicing
# arr [ row_start:row_end : step , col_start:col_end : step ]

arr2 = np.array([ [1,2,3],
                  [4,5,6]])
#print(arr2)

#Getting a row

row_0 = arr2[0:1,]
row_1 = arr2[1:,]

#print(row_0)
#print(row_1)

col_0 = arr2[::,0:1]
col_1 = arr2[::,1:2]

print(col_0)
print(col_1)

#Getting a portion 

portion = arr2[:: , 0:2]
print(portion)

[[1]
 [4]]
[[2]
 [5]]
[[1 2]
 [4 5]]
